#!/bin/bash

file=~/.photo.jpg
RED='\033[0;31m'

if [ $# -eq 1 ]; then

    curl -o "$file" "$1" &> /dev/null

    file_size=$(wc -c < "$file")
    file_size_mb=$(bc <<< "scale=2; $file_size / 1000000")

    echo "File size: $file_size_mb MB"

    if file "$file" | grep -qE 'image|bitmap'; then
        open -a Preview "$file"
    else
        echo -e "${RED}Your photo is not valid."
    fi

    sleep 1

    rm "$file"
 
else
    echo -e "${RED}You must provide the photo link."
fi
